### ISSUE TITLE
Suggestion: add a tag for music to play in caves

### ISSUE THREAD

**Issue by StardustPassingBy** [someaddons/biomemusic#11]
Being able to import custom music to play in caves / while underground would be great, because currently Minecraft doesn't seem to have a trigger for caves in general, only specific cave biomes, e.g. lush caves.

**Comment by someaddons** [comment]
Question is which music would be played there then, or just custom/specified music only?

**Comment by StardustPassingBy** [comment]
> Question is which music would be played there then, or just custom/specified music only?

Just for custom music would be a big help, I'm not sure about what vanilla music would play there.

Edit: Also, I would suggest integration for underwater or ocean music as well, since water is one of the other major music categories, and it actually does have specific music.

**Comment by Acenthus** [comment]
Adding a comment cause I'd also like to see this added at some point.

**Comment by Jszp03** [comment]
there is a mod that does that, i fogot the name but if u find it tag me

**Comment by someaddons** [comment]
added cave and ocean additional music options
