### ISSUE TITLE
music doesn't stop between (what could be considered) biomes

### ISSUE THREAD

**Issue by ThatLittleCrab** [someaddons/biomemusic#19]
An entire song will still play between the areas/biome when they really don't fit.
    eg. after a night song plays, it won't end after you sleep.

**Comment by someaddons** [comment]
biomes change quite often, due to smaller 3d biomes we have nowadays. But for sleeping I can add a skip on night songs

**Comment by someaddons** [comment]
@ThatLittleCrab I think I found a good way to smartly stop playing most musics, including biomes(those are time based now), try version 2.5
