### ISSUE TITLE
Quick question about the scope of this mod.

### ISSUE THREAD

**Issue by bruglet** [someaddons/biomemusic#2]
Does it support configuring or adding new songs for specific biomes? All the documentation says is that it can add additional songs for a dimension as a whole.

Also, would it be possible to add more than 10 music tracks per dimension (or possibly biome) or is it limited to 10 at most?

**Comment by someaddons** [comment]
specific biomes you can do via biome datapack, yes more than 10 would in theory be possible

**Comment by StardustPassingBy** [comment]
Just wanted to confirm that it is indeed possible to make the game play more than 10 songs for each included category by including a modified sounds.json in a resource pack.

**Comment by MotMomet** [comment]
> Just wanted to confirm that it is indeed possible to make the game play more than 10 songs for each included category by including a modified sounds.json in a resource pack.

is it possible somehow can you share ur resourcepack/datapack with me as example to learn?
