### ISSUE TITLE
Music is playing yet there is no sound??

### ISSUE THREAD

**Issue by Existential-Person** [someaddons/biomemusic#24]
I've been having an issue with biome music not playing and troubleshooting for hours, so I finally decided to come here for any potential help. I have been skeptical that I have been doing the resource pack right because I only have 5 songs each: end, game, nether, cave, and night. I don't know if the issue was that I needed 10 songs for it to work, but I am not searching 13 more eons for more songs so I will infer that isn't the problem. So I made an entirely clean slate, a new profile with only biome music and cupboard because the mod needs it to function. I changed around some of the configs so that it would log and show when music was playing, so I proceeded to sit around for around 5 minutes and saw the custom music playing "assets/biomemusic/sounds/music/game/game3" and then I hear nothing. I am confused because I changed the .mp3 music files to .ogg files and did it in File Explorer, do I require a _special_ converter? Possibly the file type isn't the issue. Fortunately, I can still play the .ogg files in the media player completely fine, it just won't do anything in Minecraft. I would be profoundly thankful to anyone with a solution to this daunting problem I face. (My brain is concurrently frying.) Minecraft Version: 1.20.1 Forge Version: 47.3.0

[2024-09-15](https://github.com/user-attachments/assets/1ea1e7b1-2301-401a-9f74-a40e779d0cfe)

**Comment by Existential-Person** [comment]
You know what **5$** or a month of discord **nitro basic** to the first person who can help solve my issue or walk me through this! I cannot figure it out for the life of me.

**Comment by someaddons** [comment]
yes you cannot just rename mp3 to ogg, needs to be converted via e.g. audacity or another tool.

**Comment by Existential-Person** [comment]
Well, it seemed to work. I appreciate the help! And as promised, let me know if you would like the month of Nitro Basic. 👍

**Comment by Existential-Person** [comment]
_The issue has been solved._ Discord: **Just_A_Hobo** (Just in case)

**Comment by Existential-Person** [comment]
_The issue has been solved._ Discord: **Just_A_Hobo** (Just in case)
