### ISSUE TITLE
Default music still plays even when disabled

### ISSUE THREAD

**Issue by llenkha** [someaddons/biomemusic#6]
Base game music still plays in between custom music even when "disableDefaultMusicInDimensions" is set to true

**Comment by Joshernoob** [comment]
just a guess but doesnt that only work for the nether and end? as far as i can see there is no config setting to fully prevent overworld default music in the overworld itself

**Comment by llenkha** [comment]
> just a guess but doesnt that only work for the nether and end? as far as i can see there is no config setting to fully prevent overworld default music in the overworld itself

I assumed that the option was able to completely disable default music in all dimensions and play only custom tracks if it it was only intended to disable it in the nether and end i would hope to see it be a future update to make it work in the overworld as well

**Comment by someaddons** [comment]
Biome music adds overworld music randomly to the end/nether dimensions as they're lacking non-biome based musics, turning off that config disables this
