### ISSUE TITLE
[Suggestion] Option to not play music when specific sound effects are playing

### ISSUE THREAD

**Issue by emihead** [someaddons/biomemusic#8]
Hi, I'm using this mod in my Cobblemon modpack. I have a resource pack that adds battle music to Cobblemon, but the problem is, I believe they count as sound effects rather than music. Whenever a battle starts, the current music is stopped, but a new song immediately starts since Minecraft detects that no music is playing.

Basically, I think it'd be great if this mod could be configured to prevent new songs from starting when a specific list of sound effects are playing. I'm not sure if it's possible to detect if a sound is playing with a Minecraft mod but if it is, this is an addition that would be amazing to have.

**Comment by someaddons** [comment]
That only works if mods properly set the sound type to music, so up to the battle music to use the right category
