### ISSUE TITLE
Question: How to config this mod in game, etc.

### ISSUE THREAD

**Issue by CloserPopcorn20** [someaddons/biomemusic#9]
Version: 1.20.1, Fabric
So, I have a bunch of questions about this mod:
1) When I add this mod, I can't configurate it, because there is no such option in-game (checked audio - no, checked modlist - also no)
2) Can I add only 1 soundtrack for each specific biome (for example, I want to add "The Temple of the Sleeper" (from RPG game Gothic I) to the Deep Dark biome)

Thanks for the possibility to write questions like this!

**Comment by IvorAmlug** [comment]
Sadly i dont think thats possible. There once was a mod for that called Ambient music but its long dead

**Comment by v4victory66** [comment]
Try this path:
minecraft\Instances\"your saved game "\config\biomemusic.json
open with wordpad

**Comment by someaddons** [comment]
you can do biome-specific music through vanilla datapacks already, check e.g. this: https://www.reddit.com/r/Minecraft/comments/k8m68z/perbiome_music_via_resource_pack/
or one of the youtube tutorials for it
